generator: admingenerator.generator.propel
params:
    model: C33s\SimpleContentBundle\Model\ContentPage
    namespace_prefix: C33s
    concurrency_lock: ~
    bundle_name: SimpleContentBundle
    i18n_catalog:   C33sSimpleContent
    pk_requirement: ~
    embed_types: []
    fields:
        content_type:
            addFormOptions:
                required: false
        template:
            addFormOptions:
                required: false
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    nested_list:
        params:
            title: Content pages
            display:
              - id
              - name
              - title
              - content_type
              - template
#               enable those for debugging purposes
#              - tree_left
#              - tree_right
#              - tree_level
              - is_published
              - updated_at
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:
              - is_published
    new:
        params:
            title: Add content page
            display:
              - name
              - title
              - content
              - content_type
              - template
              - is_published
            actions:
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Edit content page \"%title%\" |{ %title%: ContentPage.title }|"
            display:
              - name
              - title
              - content
              - content_type
              - template
              - is_published
            actions:
                save-and-list: ~
                list: ~
#    show:
#        params:
#            #title: "You're viewing the object \"%object%\"|{ %object%: content_page.title }|"
#            title:  "Content page details"
#            display: ~
#            actions:
#                list: ~
#                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
                