generator: admingenerator.generator.propel
params:
    model: c33s\SimpleContentBundle\Model\ContentType
    namespace_prefix: c33s
    concurrency_lock: ~
    bundle_name: SimpleContentBundle
    i18n_catalog:   C33sSimpleContent
    pk_requirement: ~
    fields:
        content_pages:
            formType:   model
            addFormOptions:
                multiple:   true
                expanded:   true
                
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Content types
            display:
              - id
              - title
              - template_name
              - updated_at
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: []
    new:
        params:
            title: Add content type
            display:
              - title
              - template_name
              - content_pages
            actions:
                save-and-list: ~
                list: ~
    edit:
        params:
            title: ''
            display:
              - title
              - template_name
              - content_pages
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
                